# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 08:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0003_auto_20170712_1549'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hostinfo',
            options={'ordering': ('hostname',), 'permissions': (('delete_host', '删除主机'), ('edis_host', '编辑主机'), ('create_host', '创建主机'))},
        ),
    ]
